---

- name: update apt cache
  apt:
    update_cache: true
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: install pkg_mirror packages
  package:
    name: '{{ pkg_mirror_packages }}'
    state: present
